### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oscarotero** [php-gettext/Twig-Scanner#3]
@drzraf  I see this package uses GPL license instead MIT (the license used by all gettext packages).

Is there any reason for that? Would you consider to switch to the more opened MIT license?

**Comment by drzraf** [comment]
Personal preference, but basically: copyleft. **End-users** relying on the packages (phar file, ...) are provided [non-obfuscated] source code by their vendor (at the price of **developers**' freedom).
Do you forsee any actual blockers that would mandate a license change?

**Comment by oscarotero** [comment]
All gettext packages are using MIT, because it's the most opened license, used by most packages. I'd like to keep that license in this package too. GPL requires that all derivated sofware must keep the same GPL license.
